name: CI/CD Pipeline

on:
  push:
    branches: [ main ]  # Adjust this if your default branch has a different name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker Image
      run: |
        docker build -t my-flask-app .

    - name: Deploy to AWS EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.HOST }}
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass
        ssh-keyscan ${{ secrets.HOST }} >> ~/.ssh/known_hosts
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.HOST }} "docker pull my-flask-app && docker run -d -p 80:80 my-flask-app"
