name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker Image
      run: |
        docker build -t vishali1/flask-app:latest .
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username vishali1 --password-stdin
        docker push vishali1/flask-app:latest

    - name: Deploy to AWS EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.HOST }}
      run: |
        mkdir -p ~/.ssh
        echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.HOST }} >> ~/.ssh/known_hosts
        ssh -o "StrictHostKeyChecking=no" ubuntu@${{ secrets.HOST }} <<EOF
          docker pull vishali1/flask-app:latest
          docker stop flask-app || true
          docker rm flask-app || true
          docker run -d --name flask-app -p 80:80 vishali1/flask-app:latest
        EOF
